[package]
name = "rtshare"
version = "0.1.0"
authors = ["Naman Arora <naman.arora@tutanota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
